name: Github Verify CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm

      # CI check
      - run: npm ci
      
      # Prettier check
      - run: npm run format:check

      - run: npx prisma generate

      - run: npm run build
